# Generated by Django 3.1.1 on 2020-10-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolsched', 'initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ghrepo',
            options={'verbose_name_plural': 'Repositories GitHub'},
        ),
        migrations.AlterModelOptions(
            name='ghtoken',
            options={'verbose_name_plural': 'Tokens GitHub'},
        ),
        migrations.AlterModelOptions(
            name='gitrepo',
            options={'verbose_name_plural': 'Repositories Git'},
        ),
        migrations.AlterModelOptions(
            name='glrepo',
            options={'verbose_name_plural': 'Repositories GitLab'},
        ),
        migrations.AlterModelOptions(
            name='gltoken',
            options={'verbose_name_plural': 'Tokens GitLab'},
        ),
        migrations.AlterModelOptions(
            name='ighenrich',
            options={'verbose_name_plural': 'Intentions GHEnrich'},
        ),
        migrations.AlterModelOptions(
            name='ighenricharchived',
            options={'verbose_name_plural': 'Archived GitHubEnrich'},
        ),
        migrations.AlterModelOptions(
            name='ighraw',
            options={'verbose_name_plural': 'Intentions GHRaw'},
        ),
        migrations.AlterModelOptions(
            name='ighrawarchived',
            options={'verbose_name_plural': 'Archived GitHubRaw'},
        ),
        migrations.AlterModelOptions(
            name='igitenrich',
            options={'verbose_name_plural': 'Intentions GitEnrich'},
        ),
        migrations.AlterModelOptions(
            name='igitenricharchived',
            options={'verbose_name_plural': 'Archived GitEnrich'},
        ),
        migrations.AlterModelOptions(
            name='igitraw',
            options={'verbose_name_plural': 'Intentions GitRaw'},
        ),
        migrations.AlterModelOptions(
            name='igitrawarchived',
            options={'verbose_name_plural': 'Archived GitRaw'},
        ),
        migrations.AlterModelOptions(
            name='iglenrich',
            options={'verbose_name_plural': 'Intentions GLEnrich'},
        ),
        migrations.AlterModelOptions(
            name='iglenricharchived',
            options={'verbose_name_plural': 'Archived GitLabEnrich'},
        ),
        migrations.AlterModelOptions(
            name='iglraw',
            options={'verbose_name_plural': 'Intentions GLRaw'},
        ),
        migrations.AlterModelOptions(
            name='iglrawarchived',
            options={'verbose_name_plural': 'Archived GitLabRaw'},
        ),
        migrations.AlterModelOptions(
            name='imeetupenrich',
            options={'verbose_name_plural': 'Intentions MeetEnrich'},
        ),
        migrations.AlterModelOptions(
            name='imeetupenricharchived',
            options={'verbose_name_plural': 'Archived MeetupEnrich'},
        ),
        migrations.AlterModelOptions(
            name='imeetupraw',
            options={'verbose_name_plural': 'Intentions MeetRaw'},
        ),
        migrations.AlterModelOptions(
            name='imeetuprawarchived',
            options={'verbose_name_plural': 'Archived MeetupRaw'},
        ),
        migrations.AlterModelOptions(
            name='meetuprepo',
            options={'verbose_name_plural': 'Repositories Meetup'},
        ),
        migrations.AlterModelOptions(
            name='meetuptoken',
            options={'verbose_name_plural': 'Tokens Meetup'},
        ),
    ]
