# Generated by Django 3.1.1 on 2020-10-15 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poolsched', 'initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMeetupRawArchived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('completed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OK', 'Success'), ('ER', 'Error')], default='OK', max_length=2)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched.meetuprepo')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IMeetupRaw',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched.meetuprepo')),
            ],
            options={
                'db_table': 'poolsched_meetupiraw',
            },
            bases=('poolsched.intention',),
        ),
        migrations.CreateModel(
            name='IMeetupEnrichArchived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('completed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OK', 'Success'), ('ER', 'Error')], default='OK', max_length=2)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched.meetuprepo')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IMeetupEnrich',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poolsched.intention')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poolsched.meetuprepo')),
            ],
            options={
                'db_table': 'poolsched_meetupienriched',
            },
            bases=('poolsched.intention',),
        ),
    ]
