# Generated by Django 3.1.1 on 2020-10-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolsched', '0001_auto_20201022_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='machine',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
